# Generated by Django 5.1.3 on 2025-04-19 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('téléphone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Depanneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=100)),
                ('disponibilité', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Depannage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_depannage', models.CharField(choices=[('batterie', 'Batterie'), ('pneu', 'Pneu'), ('mécanique', 'Mécanique'), ('remorquage', 'Remorquage'), ('autre', 'Autre')], max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminé', 'Terminé')], default='en_attente', max_length=20)),
                ('date_depannage', models.DateTimeField(auto_now_add=True)),
                ('client_longitude', models.FloatField()),
                ('client_latitude', models.FloatField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('depanneur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.depanneur')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeDepannage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depanneur_latitude', models.FloatField()),
                ('depanneur_longitude', models.FloatField()),
                ('suivi_depanneurcol', models.CharField(max_length=100)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('depannage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.depannage')),
            ],
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField(blank=True)),
                ('date_avis', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('depannage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.depannage')),
                ('depanneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.depanneur')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(max_length=50)),
                ('transaction', models.CharField(max_length=100)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('depannage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.depannage')),
            ],
        ),
    ]
