# Generated by Django 5.1.3 on 2025-04-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_client_nom_client_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='téléphone',
            new_name='telephone',
        ),
    ]
