# Generated by Django 5.1.3 on 2025-04-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_téléphone_client_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
