# Generated by Django 5.1.3 on 2025-05-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_client_latitude_alter_client_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depanneur',
            name='location',
        ),
        migrations.AddField(
            model_name='depanneur',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depanneur',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depanneur',
            name='nom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depanneur',
            name='tel',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
