# Generated by Django 5.1.3 on 2025-05-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_depanneur_location_depanneur_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depanneur',
            old_name='disponibilité',
            new_name='disponibilite',
        ),
    ]
