# Generated by Django 5.1.3 on 2025-05-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_disponibilité_depanneur_disponibilite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandedepannage',
            name='depanneur_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demandedepannage',
            name='depanneur_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depannage',
            name='client_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='depannage',
            name='client_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
