# Generated by Django 5.1.3 on 2025-05-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_demandedepannage_depanneur_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depannage',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
