# Generated by Django 5.1.3 on 2025-05-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_depannage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='depannage',
            name='prix',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
