# Generated by Django 5.1.3 on 2025-05-24 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_depannage_status_depanneurexterne'),
    ]

    operations = [
        migrations.AddField(
            model_name='depannage',
            name='depanneur_externe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.depanneurexterne'),
        ),
    ]
