# Generated by Django 5.1.3 on 2025-06-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='depanneur',
        ),
    ]
